### ISSUE TITLE
Devices timing out with 0.9.2 and 0.9.1

### ISSUE THREAD

**Issue by monsieurlatte** [jason0x43/hacs-hubitat#209]
Still need time to test but I'm getting device not responding to commands calling from HA to hubitat, seems to run fine when calling from hubitat directly, I was on 0.8.6 and that was fine (upgrading to 0.9.2 and .1 also messed with some of my device names but easily fixed fyi).  HA on 2023.4.4 and hubitat on 2.3.5.125.

**Comment by monsieurlatte** [comment]
Can confirm rolling back to .8.6 and all devices respond and turn off and on correctly (instantly).  Back to .9.2 and sometimes it's instant but often it's 15-30 seconds if they respond to a command if at all.

**Comment by kummerr** [comment]
I also have a significant number of lights (19) that are still unavailable after updating from  0.9.0 to 0.9.1.  These include both zigbee and zwave devices.  Rolling back to 0.8.6 resolves this issue.

**Comment by jason0x43** [comment]
Please try enabling debug logging and see if anything shows up there.

Is there anything different/special about the 19 lights that aren’t responding? Like, are they all rgbw and other lights aren’t?

**Comment by monsieurlatte** [comment]
Mine are all zwave.  On Apr 13, 2023, at 7:10 PM, Jason Cheatham ***@***.***> wrote:﻿
Please try enabling debug logging and see if anything shows up there.
Is there anything different/special about the 19 lights that aren’t responding? Like, are they all rgbw and other lights aren’t?

**Comment by kummerr** [comment]
Here's an excerpt of the debug log.  Not sure what it means but all of the devices on this list are not responding.  There isn't anything different or special about the devices on this list.  I have other devices of the same type that are working.

![Screen Shot 2023-04-13 at 10 20 16 PM](https://user-images.githubusercontent.com/22422493/231941039-74625eba-244b-44fc-8f59-a5cf33d0f2eb.png)

**Comment by jason0x43** [comment]
Hmmm...a lot of those devices don't seem like they should be event emitters. Currently, the only things that are (or should be) added as event emitters are devices that can act as button controllers -- ones with PushableButton, HoldableButton, DoubleTapableButton, or ReleasableButton. Are they added as HubitatEventEmitter when you're running v0.8.6, or only with v0.9.x?

**Comment by monsieurlatte** [comment]
I'm having similar issues and I didn't test .9.x but it works perfectly with .8.6

**Comment by kummerr** [comment]
They were added as HubitatEventEmitter only with v0.9.x?  Version .0.9.4 seems to have resolved this issue.

**Comment by monsieurlatte** [comment]
.9.4 seems to be working a lot better, I'm still getting random timeouts but nothing that is atrocious.  .8.6 still seems to be rock solid and always responding.

**Comment by jason0x43** [comment]
Hmmm… without more information, I’m really not sure what might be going on here. I haven’t been able to reproduce that locally, and there’s nothing in 0.9.x that should have affected the ability to connect to devices. There’s definitely nothing in 0.9.4 that should have changed the behavior from 0.9.3. The only disruptive change (that I’m aware of) in 0.9 was switching HA device names to use the Hubitat `name` property rather than `label`, and that’s been reverted.

Of course, that doesn’t mean there isn’t an issue, we just need to nail down what it is. 🙂 

Are you actually seeing any sort of timeout error in the logs, or are devices just slow to respond when issuing commands from HA? When issuing commands from HA, does the log show commands being immediately sent to Hubitat?

**Comment by jason0x43** [comment]
Is this issue still happening?
