### ISSUE TITLE
state_class missing after upgrading from 0.8.x to 0.9.8

### ISSUE THREAD

**Issue by cvinhaes** [jason0x43/hacs-hubitat#225]
Updated the integration today from an old version, hoping that the state_class would show for my existing temperature and power (from smart sockets) sensors reading from my hubitat hub, but nothing changed. Is there any additional configuration required. I've rebooted HA more than once and managed to add state_class using a global customization, but I was hoping it would come straight from the integration. Hubitat currently in v: 2.3.5.146

**Comment by kevdliu** [comment]
Noticed this after updating as well. Sensor entities are missing their device_class attributes. Binary sensors are working properly however.

**Comment by CaptainKarma** [comment]
I lost functionality for my contact and temperature/humidity sensors, had to implement a workaround to add device_class for everything to work again;

homeassistant:
  customize_glob:
     "sensor.s_*_battery*":
       device_class: battery
     "sensor.t_h_*battery*":
       device_class: battery

**Comment by jason0x43** [comment]
v0.9.12 fixes the missing device classes. I've also verified that sensor entities are reporting state classes. Give that a try.

**Comment by xvz** [comment]
I upgraded to 0.9.14, deleted and re-added my hub to check the entity generation. Device classes are working correctly now but all the entity ID suffices are missing. For example, instead of `sensor.room_battery`, it is just `sensor.room`. Similarly, instead of `binary_sensor.room_water`, it is `binary_sensor.room`. Similarly for `_last_update_time`, `_contact`, `_tamper`, etc.

**Comment by jason0x43** [comment]
I need to write more unit tests. 🤦‍♂️

**Comment by jason0x43** [comment]
That issue is fixed in 0.9.15.
