### ISSUE TITLE
Entity XXXX is incorrectly being triggered for updates while it is disabled. 

### ISSUE THREAD

**Issue by djashjones** [jason0x43/hacs-hubitat#28]
Your plug-in was the main reason why I brought a HE so many thanks for your efforts, your a star!!!

I disable certain entities that I do not use but when I restart HA I get this error.

Entity sensor.office_blind_temperature is incorrectly being triggered for updates while it is disabled. This is a bug in the hubitat integration.

**Comment by jason0x43** [comment]
Interesting. I hadn't tried disabling entities on the Home Assistant side before, and it looks like there's some behavior I haven't implemented. I'll work on that.

In the mean time, and because it would be more efficient anyway, you may want to only select devices you care about in the Maker API in Hubitat. That way Hubitat won't be wasting resources sending updates for them to Home Assistant (which it will do even if you disable them on the Home Assistant side).

**Comment by djashjones** [comment]
My Hubitat is only acting as a z-wave controller for Home assistant. For sensors I tend to zigbee devices via deconz but thanks for the heads up :)

**Comment by jason0x43** [comment]
> My Hubitat is only acting as a z-wave controller for Home assistant. For sensors I tend to zigbee devices via deconz 

Hmmm...what do you mean? The error you mentioned indicates that that the Hubitat integration is trying to update the state of a disabled sensor, which must have come from the Maker API on Hubitat.

**Comment by djashjones** [comment]
All my z-wave devices are on the Hubitat and I use Home assistant to control them and view states & power readings. Does that make sense?

**Comment by jason0x43** [comment]
That makes sense. I just wasn't sure how your previous comment (about z-wave vs zigbee) related to this issue (the "incorrectly triggered updates" error).
