### ISSUE TITLE
"This entity is unavailable."

### ISSUE THREAD

**Issue by kerrylarson** [jason0x43/hacs-hubitat#295]
I just installed HA (VirtualBox on Windows 11) and am trying to setup this Hubitat integration.  The devices are added, but any Device Controls I select gives a popup error message:  "**This entity is unavailable.**"  Integration was reloaded and HA restarted.  Looking at the Troubleshooting section for 'Devices aren't updating', I'm uncertain how to proceed.  HA is on a bridged adapter and is available on the same LAN.  On Hubitat Maker API settings, I left everything at default other than selecting devices.  "URL to POST device events to" was left blank.  If I do add the address in that section, it appends a port number.  I don't know how/where I would use that port number.

What am I doing wrong?  Thanks very much any help.

**Environment**

 - Home Assistant version: 2024.11.1
 - Integration version: 0.9.37

**Comment by kerrylarson** [comment]
Apparently I just needed to wait.  Everything appears to be working now without doing anything else.

**Comment by jason0x43** [comment]
Great, I’m glad to hear things are working!

**Comment by kerrylarson** [comment]
Shoot.  I spoke too soon.  While the Hubitat devices eventually updated, they haven't updated since (8 hours).  I can control the devices via hacs-hubitat, but any changes in device status never come through.  So I could still use some help or direction?  Thanks.

**Comment by jason0x43** [comment]
It sounds like Habitat isn’t able to post events back to Home Assistant. That’s where the event server URL and port come into play.

The integration starts a server on your HA system that listens for events from Habitat. When HA starts up, the integration attempts to set the “URL to post events to” setting in the Maker API app on Hubitat to a URL that points to that server.

In a basic setup, that will be “http://<hass IP>:<server port>”. If your setup is more complex, such as if HA is running on a non-bridged VM, Hubitat might not be able to see your HA server.

In that case, you need to set the event server URL in the integration to some address that Hubitat _can_ talk to, like the address of your host machine. You’ll also want to set the port value in the integration to some value, and use that value as the value in the event server URL. So the event server URL value might be “http://<host IP>:12345”, and the port value would be set to “12345”.

**Comment by kerrylarson** [comment]
My Hubitat is accessible at http://10.10.3.80 and HA at http://10.10.3.85:8123 (on a Bridged Adapter).  I assumed that met the requirement for communication.  Is there a distinction between HA being bridged and VM being bridged?  From what I can tell from VirtualBox/Tools/Network, that address shows 192.168.56.1.  I've been Googling and still don't understand how I would map a port in VM to HA; this second part of this is what I'm stuck on: "The port should be set to some open port value (e.g., 12345), and then this port must be mapped from the host to the HA VM/container."  Could you help me with more detailed information about doing this with VirtualBox?  Thanks very much for helping me (and for this vital integration).

**Comment by kerrylarson** [comment]
Well...it's working again.  In the Hubitat integration, I chose the Reload option (three vertical dots - Reload).  It started getting events again from Hubitat.  I also noticed that Hubitat Maker API had a new entry in "URL to POST device events to":  http://10.10.3.85:38139.  This was something I had not entered myself.  I'll keep my fingers crossed that it's sorted itself out.

**Comment by jason0x43** [comment]
The bridged adapter is the important part. It's what makes your HA VM accessible on your home network.

The port mapping instructions are mostly for if there's a proxy between HA and the rest of the network, or for when HA isn't bridged. In those cases, the port you want Hubitat to talk to on the network accessible host/proxy doesn't need to be the same port that HA's server is running on (but it can be), because the host can map an external port to a different internal one. For a VM that's bridged to the network, though, there's no port mapping going on -- your VM basically looks like any other machine on the network.

Given than your HA machine is at 10.10.3.85, that URL in Maker API looks reasonable.

However, note that when reloading the integration it will download the state of all devices from Hubitat. This means that right after reloading all your device states are current and correct, so it may look like things are working, but if Hubitat can't talk to HA, eventually you'll notice that devices aren't updating any more. Try updating a couple devices (toggle a switch or a light) and make sure they update in HA.

**Comment by kerrylarson** [comment]
I've waited a few hours this time to declare success.  All of the Hubitat devices continue to update changes immediately in HA.  Thanks Jason.
