### ISSUE TITLE
Dimmer in home assistant view like a switch

### ISSUE THREAD

**Issue by maxim31cote** [jason0x43/hacs-hubitat#37]
hi,

All my dimmers in hubitat are seen as switches in home assistant I have several models of the same brand "innovelli" but the drivers are installed in hubitat

Thanks

**Comment by jason0x43** [comment]
What is the name of the driver that the dimmers are using in Hubitat?

**Comment by maxim31cote** [comment]
Inovelli Dimmer LZW31 
Inovelli Z-Wave Smart Dimmer : driver factory installed
Inovelli Z-Wave Smart Scene Dimmer : driver factory installed

all view as switches in HA

**Comment by jason0x43** [comment]
Ah, ok, you're probably running into an issue with how lights are currently identified. The integration decides if a device is a light based on the capabilities Hubitat advertises for it: things with color control are definitely lights, while things that can be switched on and off or dimmed _might_ be lights (things that aren't lights, like fan controllers, may show up as dimmers). For things that might or might not be lights, the integration guesses based on the device name. If the name contains "light", "candle", "lamp", or a number of other light-related words, it will be treated as a light, otherwise it's a switch.

I pushed an update to the integration so that it will treat dimmers as lights, because I have a feeling that's the most common case. That will be included in the next release.
