### ISSUE TITLE
Aeotec Wallmote integration

### ISSUE THREAD

**Issue by dbbabcock73** [jason0x43/hacs-hubitat#82]
Hello.
I currently use Home Assistant as a virtual machine, so do not have the ability to plug a zwave controller into the home assistant system to locally control zwave devices.  However, using Hubitat, and adding my zwave devices to the hubitat ecosystem, and then using the hacs-hubitat  plugin, I have been able to control zwave devices through that interface in HA.  This has worked with temperature, magnetic sensors, door locks, and the wallmote.  As a result of recent updates over the last month, to ensure other interfaces were functional (econet), I have lost the ability to receive button presses from my wallmotes.  The hubitat registers that the buttons are pressed, but HA does not receive the message.  HA does receive messages from my other devices however (window sensors open/close, schlage lock lock/unlock, etc).  I know that the wallmote is reporting in to HA because it is sending the battery condition of the wallmote, but it is not sending the button presses.

**Comment by jason0x43** [comment]
Try [enabling debug logging](https://github.com/jason0x43/hacs-hubitat#logging) for the integration and restart HA. Try pressing a button and see what the log says.

**Comment by dbbabcock73** [comment]
Thanks for the tip.  Using that information, I was able to see the button presses coming across to HA from hubitat.  Using this information, I have been able to create my automations using Node Red as opposed to native HA, automations.yaml.  I am not sure what happened where my wallmotes are no longer listed as entities in HA?

**Comment by jason0x43** [comment]
Hmmm... if the devices never had entities In HA, it’s probably because they’re simple button controllers. Pure button devices (ones with no sensors or other capabilities besides pushable buttons) won’t have any associated entities in HA because they don’t have any state. A button device isn’t like a switch — it has no persistent state, it just emits events.

Button devices are used as device triggers in HA automations, and their events can also be used in Node Red.

If the wallmote used to have some associated entity in HA but no longer does, there could be some other issue.

**Comment by jason0x43** [comment]
Closing this since it seems to be resolved.
